/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Appointment;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author EXCALIBUR
 */
public class Best extends javax.swing.JFrame {
private String username;
    /**
     * Creates new form Best
     */
    public Best(String username) {
        this.username = username;
        initComponents();
        loadData();
    }
    
   private void loadData() {
    

    try  {
        Conn c = new Conn();// Veritabanı bağlantısını oluştur
        // En yoğun kişiyi bulma
        // SQL sorgusu: Appointtrack tablosundan en son eklenen randevunun bilgilerini getir
        String enYoğunKişiQuery = "SELECT * FROM appointtrack ORDER BY `Appointment Id` DESC LIMIT 1";
       // LIMIT 1 ile sadece en yüksek Appointment_Id'ye sahip olan kombinasyonu getirir.
        
        // PreparedStatement, SQL sorgusunu veritabanına göndermek için kullanılır
        try (PreparedStatement preparedStatement = c.a.prepareStatement(enYoğunKişiQuery)) {
            // Sorguyu çalıştır ve sonucu ResultSet nesnesine al
            ResultSet resultSet = preparedStatement.executeQuery();
// ResultSet'ten veri alabiliyorsak (bir sonraki satır varsa) işlemleri gerçekleştir
            if (resultSet.next()) {
                String enYoğunKişiAdı = resultSet.getString("username");// Aldığımız değeri arayüzdeki bir label'a set et
                enYoğunKişiTextField.setText(enYoğunKişiAdı);
            }
        }

        // En yoğun günü ve saati bulma
        // SQL sorgusu: Appointtrack tablosundan en yoğun gün ve saat bilgilerini getir
        String enYoğunGünVeSaatQuery = "SELECT `When`, `Clock`, COUNT(*) as `Appointment_Id` " +
                "FROM appointtrack GROUP BY `When`, `Clock` ORDER BY `Appointment_Id` DESC LIMIT 1";
        //COUNT(*) ifadesi, appointtrack tablosundaki gruplanmış (GROUP BY) her bir "When" ve "Clock" kombinasyonu için kaç adet kayıt olduğunu sayar. 
        
        // PreparedStatement, SQL sorgusunu veritabanına göndermek için kullanılır
        try (PreparedStatement preparedStatement = c.a.prepareStatement(enYoğunGünVeSaatQuery)) {
           // Sorguyu çalıştır ve sonucu ResultSet nesnesine al
            ResultSet resultSet = preparedStatement.executeQuery();
// ResultSet'ten veri alabiliyorsak (bir sonraki satır varsa) işlemleri gerçekleştir
            if (resultSet.next()) {
                // ResultSet'ten "When" ve "Clock" sütunlarındaki değerleri al
                String enYoğunGün = resultSet.getString("When");
                String enYoğunSaat = resultSet.getString("Clock");
// Aldığımız değerleri arayüzdeki iki Label'a set et
                enYoğunGünTextField.setText(enYoğunGün);
                enYoğunSaatTextField.setText(enYoğunSaat);
            }
        }
    } catch (Exception ex) {
        // Hata mesajını yazdır
        ex.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        enYoğunKişiLabel = new javax.swing.JLabel();
        enYoğunGünLabel = new javax.swing.JLabel();
        enYoğunSaatLabel = new javax.swing.JLabel();
        enYoğunKişiTextField = new javax.swing.JLabel();
        enYoğunGünTextField = new javax.swing.JLabel();
        enYoğunSaatTextField = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        enYoğunKişiLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        enYoğunKişiLabel.setText("Busiest Person :");

        enYoğunGünLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enYoğunGünLabel.setText("Most Preferred Day Of The Year:");

        enYoğunSaatLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enYoğunSaatLabel.setText("Most Preferred Time Of The Day:");

        enYoğunKişiTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enYoğunKişiTextField.setText("jLabel1");

        enYoğunGünTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enYoğunGünTextField.setText("jLabel2");

        enYoğunSaatTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enYoğunSaatTextField.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enYoğunGünLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enYoğunSaatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enYoğunKişiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enYoğunGünTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(enYoğunKişiTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enYoğunSaatTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enYoğunKişiLabel)
                    .addComponent(enYoğunKişiTextField))
                .addGap(92, 92, 92)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enYoğunGünLabel)
                    .addComponent(enYoğunGünTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enYoğunSaatLabel)
                    .addComponent(enYoğunSaatTextField))
                .addGap(28, 28, 28))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jLabel4.setText("Best Of Our Application");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Main Room");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Main(username).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Best.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Best.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Best.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Best.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Best("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enYoğunGünLabel;
    private javax.swing.JLabel enYoğunGünTextField;
    private javax.swing.JLabel enYoğunKişiLabel;
    private javax.swing.JLabel enYoğunKişiTextField;
    private javax.swing.JLabel enYoğunSaatLabel;
    private javax.swing.JLabel enYoğunSaatTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
